module.exports = [
  {
    id: 41,
    createdAt: "7-22",
    updatedAt: "7-30",
    categoryId: 1,
    title: "hello",
    viewNum: 12,
    content: "zilizunink",
    author: 1,
    thumbnailId: 3,
  },
  {
    id: 42,
    createdAt: "7-22",
    updatedAt: "7-30",
    categoryId: 1,
    title: "hello",
    viewNum: 12,
    content: "wunmubdulb",
    author: 1,
    thumbnailId: 3,
  },
  {
    id: 113,
    createdAt: "7-22",
    updatedAt: "7-30",
    categoryId: 1,
    title: "hello",
    viewNum: 12,
    content: "kojekizzoo",
    author: 1,
    thumbnailId: 3,
  },
  {
    id: 182,
    createdAt: "7-22",
    updatedAt: "7-30",
    categoryId: 1,
    title: "hello",
    viewNum: 12,
    content: "vinokibiti",
    author: 1,
    thumbnailId: 3,
  },
  {
    id: 138,
    createdAt: "7-22",
    updatedAt: "7-30",
    categoryId: 1,
    title: "hello",
    viewNum: 12,
    content: "begwegocbe",
    author: 1,
    thumbnailId: 3,
  },
];
